### ISSUE TITLE
About Support PHP 7.2 

### ISSUE THREAD

**Issue by mozgbrasil** [magestat/magento2-split-order#13]
Hello good afternoon

I am using Magento 2.3 and PHP 7.2, I tried to install your module and the warning was returned, can you help me

"Package magestat / module-split-order at version has a PHP requirement incompatible with your PHP version (7.2.14)"

**Comment by williankeller** [comment]
Hi @mozgbrasil, thanks for your report.
We added the compatibility with PHP 7.2 Please check our last release [v1.0.4](https://github.com/magestat/magento2-split-order/releases/tag/1.0.4)

Regards,
