### ISSUE TITLE
If multiple products in cart from same vendor giving wrong totals

### ISSUE THREAD

**Issue by dineshmanne** [magestat/magento2-split-order#16]
I really loved this extension , Lets say i have 2 vendors with 200 products each. A customer selected 2 Products from one vendor and one from other vendor. The Grand Total is not showing correct for the first vendor (with 2 products). I am using a GST module to update the tax caluculations. Does this effects your total calculations?

**Comment by yamineesowri** [comment]
yaa grand total is wrong for me if the order has 2 items.

please give me fix for this

**Comment by williankeller** [comment]
Hi,
Could you describe the version you’re using, and if the error occurs in a fresh installation?

**Comment by dineshmanne** [comment]
I am using Magento 2.2

**Comment by yamineesowri** [comment]
i am using 2.2.7 with default luma theme fresh installation

**Comment by dineshmanne** [comment]
I think that you are not calculating subtotal and grandtotal if multiple products from same vendor.

**Comment by yamineesowri** [comment]
i just tested with product weight attribute even though grand total is displaying one last item only

**Comment by yamineesowri** [comment]
i think this is the function right

    public function recollectTotal($quotes, $item, $quote, $addresses)
    {
        // Retrieve values.
        $tax = $item->getData('tax_amount');
        $discount = $item->getData('discount_amount');

        $finalPrice = ($item->getPrice() * $item->getQty());

        // Set addresses.
        $quote->getBillingAddress()->setData($addresses['billing']);
        $quote->getShippingAddress()->setData($addresses['shipping']);

        // Add shipping amount if product is not virual.
        $shipping = $this->shippingAmount($quotes, $quote);

        // Recollect totals into the quote.
        foreach ($quote->getAllAddresses() as $address) {
            // Build grand total.
            $grandTotal = (($finalPrice + $shipping + $tax) - $discount);

its not looping every item only last item it took

**Comment by dineshmanne** [comment]
Yes , This is the function for calculating Grand Total And Tax Amount for each order. We have to calculate Final Price Depends on Number of products from same vendor.

**Comment by yamineesowri** [comment]
can u help me how to do this.

i am not asking for vendor wise just default product attribute

**Comment by dineshmanne** [comment]
can anybody help me on this ?

**Comment by williankeller** [comment]
@viniciusfabri

**Comment by viniciusfabri** [comment]
Hi @dineshmanne @yamineesowri, please try applying the fix in this PR: https://github.com/magestat/magento2-split-order/pull/21

There are a couple of issues in that PR, if you'd like you can apply only the commit related to this issue: https://github.com/magestat/magento2-split-order/pull/21/commits/b81084ad9df9d38371ea486464d5249556b4967a

**Comment by dineshmanne** [comment]
Hi Vinicius , Thanks for your PR. It is not splitting shipping amount and tax amount also showing wrongly. Can you please look into this?

**Comment by dineshmanne** [comment]
Hi Vinicius , Its working perfectly. thank you

**Comment by williankeller** [comment]
Since the bug was fixed, closing this issue.
