### ISSUE TITLE
Split Order Not working in Stripe

### ISSUE THREAD

**Issue by ubaidullaazeem** [magestat/magento2-split-order#18]
Hi,

Currently we are using [ free stripe extension](https://github.com/PowerSync/TNW_Stripe). We are try to split the order then getting the error **Must provide source or customer.** 

Please can you provide the solution for above issue.

**Comment by williankeller** [comment]
Hi @ubaidullaazeem, unfortunately, it's a known issue. magento doesn't allow use multiples shipping with external payment methods. Please refer to the discussion here: https://github.com/magestat/magento2-split-order/issues/10.
Let us know if you have any suggestions.

**Comment by ubaidullaazeem** [comment]
OK thanks for the update. Can you please tell us Split Order working for which payment method ?

**Comment by williankeller** [comment]
The module uses the same process as multi-shipping. That's the reason you're unable to use it

**Comment by ubaidullaazeem** [comment]
Hi,
The [mage2pro](https://github.com/mage2pro/stripe) stripe support multi-shipping. Can you please update your code based on that.

**Comment by williankeller** [comment]
As mentioned before, please follow this issue: https://github.com/magestat/magento2-split-order/issues/10#issuecomment-452299184
