### ISSUE TITLE
main.CRITICAL: Warning: count(): Parameter must be an array or an object that implements Countable in app/code/Magestat/SplitOrder/Block/Checkout/Success.php on line 64

### ISSUE THREAD

**Issue by binnykumar** [magestat/magento2-split-order#22]
### Preconditions

1. Magento 2.3.1
2. PHP 7.2

### Steps to reproduce

1. Create custom product attributes with dropdown option value. In my case i added two option value A and B. or Create custom product attributes with text field. In my case i added two option value A and B for two different product.
2. Add these two product in cart with qty 1 for each or multiple.
3. Proceed to checkout and place order.

### Expected result

1. [Screenshots, logs or description]
![expected](https://user-images.githubusercontent.com/29915861/57926653-75b3fb80-78c9-11e9-9808-b19f052640c6.png)

Note: Working with product attribute SKU.

### Actual result

1. [Screenshots, logs or description]
![error](https://user-images.githubusercontent.com/29915861/57926694-8f554300-78c9-11e9-8acc-cb3b9bc6790b.png)

main.CRITICAL: Warning: count(): Parameter must be an array or an object that implements Countable in app/code/Magestat/SplitOrder/Block/Checkout/Success.php on line 64 [] []

**Comment by binnykumar** [comment]
I fixed it by adding condition 

// If number of orders is just like one, kill function.
        if (is_array($splittedOrders)) {
            if (count($splittedOrders) <= 1) {
                return false;
            }
        }

error is fixed but order is not splitting. Its coming as a single order.

**Comment by binnykumar** [comment]
Hi @williankeller , this seems working fine.

you can close this issue.

**Comment by williankeller** [comment]
@binnykumar, what actually was your issue about?

**Comment by binnykumar** [comment]
@williankeller, i am not facing this issue now. 

thnaks
