### ISSUE TITLE
Splitting Order Based on Stock Status of product in cart

### ISSUE THREAD

**Issue by saigadekar** [magestat/magento2-split-order#26]
Hi 

I am Using Magento 2.3.1 community Edition.

I am trying to split the order based on the Stock Status of the product Meaning if User is adding two products in which if 1 product is in stock and other 1 in outofstock (backorder enabled) then it should create two separate orders 1 for instock and other for outofstock. 

Please let me know if this is possible in current developed plugin or help in which i can achieve this.

Right now in magento 2.3.1 the main quantity is not getting updated (deducted) once you place the order .rather it shows saleable quantity text qty in product edit

**Comment by williankeller** [comment]
Hi @saigadekar, When you enable the "backorder" functionality, the product never get "out of stock", only their inventory size get decreased. If you want an "out of stock" product, you should set it as "out of stock"

**Comment by saigadekar** [comment]
Hi @williankeller 

So you mean to say if i have 1 instock and 1 outofstock (backorder enabled) product in my cart then it will generate 2 orders if i split on quantity product attribute.

**Comment by williankeller** [comment]
@saigadekar,
Please refer the Pull Request https://github.com/magestat/magento2-split-order/pull/27, we did some improvements to make sure the stock is returning the expected value base on the _Quantity_ attribute.
Now you're able to select some options including backorder configuration.
![image](https://user-images.githubusercontent.com/2963928/58709250-0efb0b80-83ba-11e9-95b0-82e1beb74d1c.png)
This Pull Request will be merged and a new release will be generated soon.

**Comment by williankeller** [comment]
Changes available under the last release https://github.com/magestat/magento2-split-order/releases/tag/1.0.6
