### ISSUE TITLE
Currency Conversion Issue

### ISSUE THREAD

**Issue by saigadekar** [magestat/magento2-split-order#30]
if multi currency is enabled on your website and you are placing order then price which is getting updated in order doesn't get converted into the base currency price.

e.g. I placed an order where currency was selected as Rupees(india) and my base currency was Dollar but the price which is shown is same for both currencies.

Screenshot Before activating the plugin.

![image](https://user-images.githubusercontent.com/12250864/58799810-e9713a80-8623-11e9-887a-e9f9295d1cb2.png)

After Activating the plugin
![image](https://user-images.githubusercontent.com/12250864/58800097-a2d01000-8624-11e9-8e43-35b5b7746521.png)

**Comment by saigadekar** [comment]
I could Achieve this using following code . just pass the value in convertPrice() and get the base currency converted code and save the same to base currency: Add below code in QuoteHander.php model file

            $address->setBaseSubtotal($baseFinalPrice);
            $address->setSubtotal($finalPrice);
            $address->setDiscountAmount($discount);
            $address->setBaseDiscountAmount($baseDiscount);
            $address->setTaxAmount($tax);
            $address->setBaseTaxAmount($baseTax);
            $address->setBaseGrandTotal($baseGrandTotal);
            $address->setGrandTotal($grandTotal);

Conversion functions


`/**
 * @var \Magento\Store\Model\StoreManagerInterface
 */
protected $storeManager;

/**
 * @var \Magento\Directory\Model\CurrencyFactory
 */
protected $currencyFactory;

/**
 * @param \Magento\Store\Model\StoreManagerInterface $storeManager
 * @param \Magento\Directory\Model\CurrencyFactory $currencyFactory
 */
public function __construct(
    \Magento\Store\Model\StoreManagerInterface $storeManager,
    \Magento\Directory\Model\CurrencyFactory $currencyFactory
) {
    $this->storeManager = $storeManager;
    $this->currencyFactory = $currencyFactory;
}

/**
 * Convert base price value to store price value
 *
 * @param $amountValue
 * @return float
 */
public function convertPrice($amountValue)
{
    $currentCurrency = $this->storeManager->getStore()->getCurrentCurrency()->getCode();
    $baseCurrency = $this->storeManager->getStore()->getBaseCurrency()->getCode();
    if ($currentCurrency != $baseCurrency) {
        $rate = $this->currencyFactory->create()->load($currentCurrency)->getAnyRate($baseCurrency);
        $amountValue = $amountValue * $rate;
    }

    return $amountValue;
}`

**Comment by williankeller** [comment]
Hi @saigadekar, this is a free community module, feel free to contribute by creating a pull request ;)
