### ISSUE TITLE
After installing this plugin , checkout is not working

### ISSUE THREAD

**Issue by thangasujithas** [magestat/magento2-split-order#34]
After installing this plugin , checkout is not working.. It keeps loading.

**To Reproduce**
1. Install the plugin in live site.
2. Set Product Attribute to Split as "SKU" in backend
3. Add the product to cart
4. Go to checkout page and fill the shipping and payment details..The page keeps loading only

**Expected behavior**
After filling the shipping and payment details..The order should be placed without an issue.

**Additional context**

Kindly give the solution to solve it.

**Comment by williankeller** [comment]
Hi @thangasujithas,
Could you share the Magento version, also if it is as EE or CE.

**Comment by thangasujithas** [comment]
Magento 2.2.5. CE. It conflicts with the medma marketplace extension. It shows "From header set twice" Exception in system.log file

**Comment by williankeller** [comment]
Hi @thangasujithas,
Could you share the completely Exception in system.log file?

**Comment by williankeller** [comment]
Closing this issue as we didn't get any feedback
