### ISSUE TITLE
Server error on checkout

### ISSUE THREAD

**Issue by jtw2568** [magestat/magento2-split-order#36]
### Preconditions

1. Magento 2.2.6
2. php 7.0

### Steps to reproduce

1. Place an item with the category trunk with any other item category  
2. follow checkout as normal
3. use a credit card for the purchase 

### Expected result

1. order should be successful 

### Actual result

1. upper right-hand corner shows An error occurred on the server. Please try to place the order again.
![image](https://user-images.githubusercontent.com/58995715/71035894-7ffdd880-20ea-11ea-9379-003785029995.png)

**Comment by williankeller** [comment]
Hi @jtw2568
Can you attach also your logs? We'd like to see if the server is responding with some exceptions.
I'm closing the issue, for now, feel free to reopen if you already have the logs.
