### ISSUE TITLE
Getting error when I click Split Order on admin config page

### ISSUE THREAD

**Issue by balasivagnanam** [magestat/magento2-split-order#38]
**Magento version**
Version 2.3.0 
**Magento edition:**
Community Edition

**Describe the bug**
Installation was successful after loading the files to the directory
After enabling, setup-upgrade and cache clear. When I go to admin page and click on split order I get an error.

1 exception(s):
Exception #0 (ReflectionException): Class Magestat\SplitOrder\Model\Config\Source\Attributes does not exist

Exception #0 (ReflectionException): Class Magestat\SplitOrder\Model\Config\Source\Attributes does not exist
#0 /home/synergo/public_html/staging/magento2/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magestat\\SplitO...')
#1 /home/synergo/public_html/staging/magento2/vendor/magento/framework/ObjectManager/Definition/Runtime.php(49): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magestat\\SplitO...')
#2 /home/synergo/public_html/staging/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magestat\\SplitO...')
#3 /home/synergo/public_html/staging/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magestat\\SplitO...')
.......

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Configuration'
3. Scroll down to 'Magestat -> Split Order'

**Expected behavior**
Suppose it should show the Page for configuration

**Screenshots**
<img width="1231" alt="Screenshot 2020-03-20 at 12 23 38 PM" src="https://user-images.githubusercontent.com/4233785/77135273-aba3ac80-6aa5-11ea-8f74-86d3c2cc1d54.png">

**Comment by williankeller** [comment]
Hi @balasivagnanam,
Thank you for let us know. You said `loading the files to the directory` what exactly it means?
Did you clone the repository?
What is the folder structure?

**Comment by balasivagnanam** [comment]
I mean I dowloaded the files and FTPed to my server.
below is my file structure.

> public_html/staging/magento2/app/code/MageStat/SplitOrder

magento 2 is my root folder.

And below is my file/directories that you can see in the server.
<img width="901" alt="Screenshot 2020-03-22 at 8 23 07 AM" src="https://user-images.githubusercontent.com/4233785/77239504-8e422000-6c16-11ea-82e7-cc861d33f1ed.png">

And below here is the file that the error says which is missing. But I could see it in the server already.
<img width="930" alt="Screenshot 2020-03-22 at 8 23 26 AM" src="https://user-images.githubusercontent.com/4233785/77239518-aa45c180-6c16-11ea-819b-4fb7bf4ac68d.png">

**Comment by williankeller** [comment]
Hello!
You are using the wrong folder name. The vendor name should be “Magestat”. There is no uppercase S. Please follow the instructions folder at the README.md.
The folder should be “/app/code/Magestat/SplitOrder”

Thank you,
Magestat team




________________________________

**Comment by balasivagnanam** [comment]
Yeh it works after I corrected it. I followed the instructions but somehow missed this part. Thanks a lot for your help.

**Comment by williankeller** [comment]
@balasivagnanam!
Happy it worked out!
We appreciate if you give us a Star ⭐️
