### ISSUE TITLE
support for adding multiple products for each quote

### ISSUE THREAD

**Issue by umarch06** [magestat/magento2-split-order#4]
I really loved this extension, this is very simple and written beautifully but I am scared if it fulfils cart price rules and other discounts. 
Moreover can you please add multi product support in this? I tried to do so but I am unable to work on collect totals method. In my case I have products with specific attributes which has to be added in separate order and remaining should be in other order.

**Comment by williankeller** [comment]
Hi @umarch06, thanks for raise these points.
We are working in a new version to make the code more simple and understandable and also to better handler to the products in cart.

Keep posted about the new releases.

**Comment by wsheldon** [comment]
Hi @williankeller Thanks so much for this extension!  I too need to extend it to add additional functionality to split on an attribute.  I'm planning to simply extend your extension unless you're also working on that.  I could submit a PR but wanted to check since I haven't started working yet.  Also, have you confirmed this works with native Braintree?  Thx!

**Comment by williankeller** [comment]
Hi @wsheldon, we’re working to release a version with the possibility to select an attribute to split
The commitment is release by next week.

Thanks!

**Comment by wsheldon** [comment]
Great, thanks! @williankeller Have you tested with native Braintree?

**Comment by williankeller** [comment]
The behavior is the same of generating just one order. Should be working normally with native Braintree.
Let us know if you have any issues with that ;)

**Comment by wsheldon** [comment]
Hi @williankeller Thanks again for all of your hard work on this.  Are you still planning to do a new release this week?

**Comment by williankeller** [comment]
Yeap @wsheldon, this feature will be released in a few days ;)

**Comment by wsheldon** [comment]
Great, thanks @williankeller

**Comment by williankeller** [comment]
Released [1.0.2](https://github.com/magestat/magento2-split-order/releases/tag/1.0.2)
