### ISSUE TITLE
Split order does not work

### ISSUE THREAD

**Issue by sergkesz** [magestat/magento2-split-order#6]
Magento v2.2.3
1. Place more than 1 product to shopping cart.
2. Proceed to checkout and complete.
3. Error occurs: order confirmation email sent even if shipping address error was showed on checkout page and success page never showed up.

Expected split order by any single product with success page shown.

**Comment by williankeller** [comment]
Fixed under release https://github.com/magestat/magento2-split-order/tree/1.0.1
